name: Countributors

on:
  push:
    branches:
      - main

jobs:
  contributor_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cjdenio/contributor_list@master
        with:
          commit_message: 'feat: update contributor list'
          max_contributors: 10
